name: 'CI'

on:
  push:
    paths-ignore:
      - 'build/**'
      - 'docs/**'
      - '.editorconfig'
      - '.gitattributes'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'build/**'
      - 'docs/**'
      - '.editorconfig'
      - '.gitattributes'
      - 'LICENSE'
      - 'README.md'

jobs:
  parallel-lint:
    name: 'ParallelLint'
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Run ParallelLint
        run: composer parallel-lint -- --no-progress --ignore-fails

  psalm:
    name: 'Psalm'
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Run Psalm
        run: composer psalm -- --no-progress --no-cache --output-format=github

  php-cs-fixer:
    name: 'PHPCsFixer'
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHPCsFixer
        run: composer php-cs-fixer:diff -- --no-interaction --using-cache=no

  phpunit:
    name: 'PHPUnit'
    needs: ['parallel-lint', 'psalm', 'php-cs-fixer']
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - 'ubuntu-latest'
          - 'windows-latest'
        php-version:
          - '8.1'
        composer-dependency:
          - 'lowest'
          - 'highest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.composer-dependency }}

      - name: Run PHPUnit
        run: composer phpunit -- --no-interaction --do-not-cache-result
