name: build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'LICENSE.txt'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'LICENSE.txt'
      - 'README.md'

jobs:
  unit-tests:
    name: Unit tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [8.1]
        stability: [prefer-lowest, prefer-stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Run Unit tests
        run: vendor/bin/phpunit --verbose --no-interaction
